### ISSUE TITLE
TypeError: Cannot convert undefined or null to object" Vue-chat

### ISSUE THREAD

**Issue by VincentBoots** [opentok/opentok-web-samples#73]
Hi,

When i run the project i get the follwing error in session.vue

Error in created hook: "TypeError: Cannot convert undefined or null to object"

the error occours in

var nodeListToArray = function nodeListToArray(nodes) {
  if (env.name !== 'IE' || env.version > 9) {
    **return Array.prototype.slice.call(nodes);**
  }

it cannot find nodes

**Comment by AkselsLedins** [comment]
Any updates on this? @VincentBoots

**Comment by abrel** [comment]
Hello,
I have the same issue.
it actually happens when I include usersnap sources in my project (https://usersnap.com/).
It seems there is a conflict between the two libraries.

```
Unhandled rejection TypeError: Cannot convert undefined or null to object    at slice (<anonymous>)    at nodeListToArray (webpack-internal:///./node_modules/@opentok/client/dist/js/opentok.js:19332:34)    at selectorToElementArray (webpack-internal:///./node_modules/@opentok/client/dist/js/opentok.js:19375:16)    at new ElementCollection (webpack-internal:///./node_modules/@opentok/client/dist/js/opentok.js:19408:18)    at module.exports (webpack-internal:///./node_modules/@opentok/client/dist/js/opentok.js:19303:10)    at Object.browserAjax.request (webpack-internal:///./node_modules/@opentok/client/dist/js/opentok.js:20222:7)    at Object.browserAjax.post (webpack-internal:///./node_modules/@opentok/client/dist/js/opentok.js:20265:17)    at eval (webpack-internal:///./node_modules/@opentok/client/dist/js/opentok.js:42272:19)    at loop (webpack-internal:///./node_modules/@opentok/client/dist/js/opentok.js:42455:7)    at QueueRunner.run (webpack-internal:///./node_modules/@opentok/client/dist/js/opentok.js:42459:5)    at QueueRunner.add (webpack-internal:///./node_modules/@opentok/client/dist/js/opentok.js:42439:10)    at post (webpack-internal:///./node_modules/@opentok/client/dist/js/opentok.js:42271:11)    at Analytics.logEvent (webpack-internal:///./node_modules/@opentok/client/dist/js/opentok.js:42392:5)    at eval (webpack-internal:///./node_modules/@opentok/client/dist/js/opentok.js:4725:25)    at eval (webpack-internal:///./node_modules/@opentok/client/dist/js/opentok.js:20885:5)    at Object.get (webpack-internal:///./node_modules/@opentok/client/dist/js/opentok.js:20893:5)
```

**Comment by shakalya195** [comment]
Please update I am facing the same issue. while session.connect(). it does not handle any error.

**Comment by aullman** [comment]
I think this is the same issue as with angular 6. Usersnap are probably overriding the XMLHttpRequest library (which they shouldn't be). Do you know if that is the case? If you're not sure it would be great if you can share the usersnap js file. I can't find it on the website.

**Comment by themohsinkhan** [comment]
@aullman the standalone application is working fine. But when I integrate it in my existing project it shows me the below error which is exactly the same error shown above. Please guide me on how to fix this as this is a critical task. Thanks in advance.
```
vue.esm.js?a026:610 [Vue warn]: Error in created hook: "TypeError: Cannot convert undefined or null to object"

found in

---> <Session> at src/components/tele-health-sp/Session.vue
       <VideoChat> at src/components/tele-health-sp/video-chat.vue
         <App> at src/components/app/app.vue
           <Root>
warn @ vue.esm.js?a026:610
logError @ vue.esm.js?a026:1824
globalHandleError @ vue.esm.js?a026:1819
handleError @ vue.esm.js?a026:1808
callHook @ vue.esm.js?a026:3036
Vue._init @ vue.esm.js?a026:4731
VueComponent @ vue.esm.js?a026:4897
createComponentInstanceForVnode @ vue.esm.js?a026:4400
init @ vue.esm.js?a026:4231
createComponent @ vue.esm.js?a026:5706
createElm @ vue.esm.js?a026:5653
createChildren @ vue.esm.js?a026:5781
createElm @ vue.esm.js?a026:5682
patch @ vue.esm.js?a026:6244
Vue._update @ vue.esm.js?a026:2777
updateComponent @ vue.esm.js?a026:2895
get @ vue.esm.js?a026:3265
run @ vue.esm.js?a026:3340
flushSchedulerQueue @ vue.esm.js?a026:3096
(anonymous) @ vue.esm.js?a026:1925
flushCallbacks @ vue.esm.js?a026:1844
Promise.then (async)
microTimerFunc @ vue.esm.js?a026:1892
nextTick @ vue.esm.js?a026:1938
queueWatcher @ vue.esm.js?a026:3188
update @ vue.esm.js?a026:3330
notify @ vue.esm.js?a026:721
mutator @ vue.esm.js?a026:873
push @ vee-validate.esm.js?7bb1:2508
attach @ vee-validate.esm.js?7bb1:2959
attach @ vee-validate.esm.js?7bb1:2581
bind @ vee-validate.esm.js?7bb1:2770
callHook$1 @ vue.esm.js?a026:6407
_update @ vue.esm.js?a026:6329
updateDirectives @ vue.esm.js?a026:6310
invokeCreateHooks @ vue.esm.js?a026:5797
createElm @ vue.esm.js?a026:5684
createChildren @ vue.esm.js?a026:5781
createElm @ vue.esm.js?a026:5682
createChildren @ vue.esm.js?a026:5781
createElm @ vue.esm.js?a026:5682
createChildren @ vue.esm.js?a026:5781
createElm @ vue.esm.js?a026:5682
createChildren @ vue.esm.js?a026:5781
createElm @ vue.esm.js?a026:5682
createChildren @ vue.esm.js?a026:5781
createElm @ vue.esm.js?a026:5682
createChildren @ vue.esm.js?a026:5781
createElm @ vue.esm.js?a026:5682
createChildren @ vue.esm.js?a026:5781
createElm @ vue.esm.js?a026:5682
createChildren @ vue.esm.js?a026:5781
createElm @ vue.esm.js?a026:5682
createChildren @ vue.esm.js?a026:5781
createElm @ vue.esm.js?a026:5682
patch @ vue.esm.js?a026:6205
Vue._update @ vue.esm.js?a026:2774
updateComponent @ vue.esm.js?a026:2895
get @ vue.esm.js?a026:3265
Watcher @ vue.esm.js?a026:3254
mountComponent @ vue.esm.js?a026:2902
Vue.$mount @ vue.esm.js?a026:8655
Vue.$mount @ vue.esm.js?a026:11070
init @ vue.esm.js?a026:4235
createComponent @ vue.esm.js?a026:5706
createElm @ vue.esm.js?a026:5653
createChildren @ vue.esm.js?a026:5781
createElm @ vue.esm.js?a026:5682
createChildren @ vue.esm.js?a026:5781
createElm @ vue.esm.js?a026:5682
patch @ vue.esm.js?a026:6205
Vue._update @ vue.esm.js?a026:2774
updateComponent @ vue.esm.js?a026:2895
get @ vue.esm.js?a026:3265
Watcher @ vue.esm.js?a026:3254
mountComponent @ vue.esm.js?a026:2902
Vue.$mount @ vue.esm.js?a026:8655
Vue.$mount @ vue.esm.js?a026:11070
init @ vue.esm.js?a026:4235
createComponent @ vue.esm.js?a026:5706
createElm @ vue.esm.js?a026:5653
createChildren @ vue.esm.js?a026:5781
createElm @ vue.esm.js?a026:5682
patch @ vue.esm.js?a026:6205
Vue._update @ vue.esm.js?a026:2774
updateComponent @ vue.esm.js?a026:2895
get @ vue.esm.js?a026:3265
Watcher @ vue.esm.js?a026:3254
mountComponent @ vue.esm.js?a026:2902
Vue.$mount @ vue.esm.js?a026:8655
Vue.$mount @ vue.esm.js?a026:11070
init @ vue.esm.js?a026:4235
createComponent @ vue.esm.js?a026:5706
createElm @ vue.esm.js?a026:5653
createChildren @ vue.esm.js?a026:5781
createElm @ vue.esm.js?a026:5682
patch @ vue.esm.js?a026:6205
Vue._update @ vue.esm.js?a026:2774
updateComponent @ vue.esm.js?a026:2895
get @ vue.esm.js?a026:3265
Watcher @ vue.esm.js?a026:3254
mountComponent @ vue.esm.js?a026:2902
Vue.$mount @ vue.esm.js?a026:8655
Vue.$mount @ vue.esm.js?a026:11070
init @ vue.esm.js?a026:4235
createComponent @ vue.esm.js?a026:5706
createElm @ vue.esm.js?a026:5653
patch @ vue.esm.js?a026:6244
Vue._update @ vue.esm.js?a026:2774
updateComponent @ vue.esm.js?a026:2895
get @ vue.esm.js?a026:3265
Watcher @ vue.esm.js?a026:3254
mountComponent @ vue.esm.js?a026:2902
Vue.$mount @ vue.esm.js?a026:8655
Vue.$mount @ vue.esm.js?a026:11070
(anonymous) @ main.js?56d7:16
./src/main.js @ app.js:7524
__webpack_require__ @ app.js:768
fn @ app.js:131
0 @ app.js:7921
__webpack_require__ @ app.js:768
(anonymous) @ app.js:904
(anonymous) @ app.js:907
Show 92 more frames
vue.esm.js?a026:1828 TypeError: Cannot convert undefined or null to object
    at slice (<anonymous>)
    at nodeListToArray (opentok.js?33ba:20056)
    at selectorToElementArray (opentok.js?33ba:20099)
    at new ElementCollection (opentok.js?33ba:20132)
    at module.exports (opentok.js?33ba:20027)
    at Object.browserAjax.request (opentok.js?33ba:20838)
    at Object.browserAjax.post (opentok.js?33ba:20881)
    at eval (opentok.js?33ba:20972)
    at loop (opentok.js?33ba:45118)
    at QueueRunner.run (opentok.js?33ba:45122)
```
